- name: setup bash fragrment loader
  blockinfile:
    dest: "{{ item }}"
    block: "{{ lookup('file', 'bash-d.sh') }}"
  with_items:
    - ~/.profile
    - ~/.bash_profile
  when: item|exists

- name: make ~/.bash.d/
  file:
    path: ~/.bash.d
    state: directory
